### ISSUE TITLE
An error when executing   make BOARD=BLACK_F470VE...

### ISSUE THREAD

**Issue by lyoncr** [mcauser/BLACK_F407VE#11]
when executing   make BOARD=BLACK_F470VE,  an error was encountered as follows:

In file included from eth.c:31:0:
eth.c: In function 'eth_mac_init':
eth.c:163:106: error: implicit declaration of function 'STATIC_AF_ETH_RMII_REF_CLK' [-Werror=implicit-function-declaration]
     mp_hal_pin_config_alt_static(MICROPY_HW_ETH_RMII_REF_CLK, MP_HAL_PIN_MODE_ALT, MP_HAL_PIN_PULL_NONE, STATIC_AF_ETH_RMII_REF_CLK);
                                                                                                          ^
pin_static_af.h:42:48: note: in definition of macro 'mp_hal_pin_config_alt_static'
         mp_hal_pin_config(pin_obj, mode, pull, fn_type(pin_obj)) /* Overflow Error => alt func not found */
                                                ^~~~~~~
cc1: all warnings being treated as errors
../../py/mkrules.mk:47: recipe for target 'build-BLACK_F407VE/eth.o' failed
make: *** [build-BLACK_F407VE/eth.o] Error 1

Anyone could explain how to resolve it ? thanks.

**Comment by mcauser** [comment]
Possibly related to this:
https://github.com/micropython/micropython/issues/5286

https://github.com/micropython/micropython/commit/258b1478307c1f9d89ed67309e145b9a55aeaadc#diff-11f1687bc533f763aa3113bcd3ae5a31

How recent is your MicroPython repo?

Pin A1's AF had `ETH_RMII__REF_CLK` instead of `ETH_RMII_REF_CLK` (double _ _ instead of single _)
